/* This file was generated by SableCC (http://www.sablecc.org/). */

package subtitulo.parser;

import subtitulo.node.*;
import subtitulo.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDigit(@SuppressWarnings("unused") TDigit node)
    {
        this.index = 0;
    }

    @Override
    public void caseTArrow(@SuppressWarnings("unused") TArrow node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTwopoint(@SuppressWarnings("unused") TTwopoint node)
    {
        this.index = 3;
    }

    @Override
    public void caseTColor(@SuppressWarnings("unused") TColor node)
    {
        this.index = 4;
    }

    @Override
    public void caseTText(@SuppressWarnings("unused") TText node)
    {
        this.index = 5;
    }

    @Override
    public void caseTOpen(@SuppressWarnings("unused") TOpen node)
    {
        this.index = 6;
    }

    @Override
    public void caseTClose(@SuppressWarnings("unused") TClose node)
    {
        this.index = 7;
    }

    @Override
    public void caseTEnd(@SuppressWarnings("unused") TEnd node)
    {
        this.index = 8;
    }

    @Override
    public void caseTFont(@SuppressWarnings("unused") TFont node)
    {
        this.index = 9;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 10;
    }
}
