/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.node;

import srt.analysis.*;

@SuppressWarnings("nls")
public final class ATextlistTextlist extends PTextlist
{
    private PTextlist _textlist_;
    private TText _text_;

    public ATextlistTextlist()
    {
        // Constructor
    }

    public ATextlistTextlist(
        @SuppressWarnings("hiding") PTextlist _textlist_,
        @SuppressWarnings("hiding") TText _text_)
    {
        // Constructor
        setTextlist(_textlist_);

        setText(_text_);

    }

    @Override
    public Object clone()
    {
        return new ATextlistTextlist(
            cloneNode(this._textlist_),
            cloneNode(this._text_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextlistTextlist(this);
    }

    public PTextlist getTextlist()
    {
        return this._textlist_;
    }

    public void setTextlist(PTextlist node)
    {
        if(this._textlist_ != null)
        {
            this._textlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textlist_ = node;
    }

    public TText getText()
    {
        return this._text_;
    }

    public void setText(TText node)
    {
        if(this._text_ != null)
        {
            this._text_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._text_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._textlist_)
            + toString(this._text_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._textlist_ == child)
        {
            this._textlist_ = null;
            return;
        }

        if(this._text_ == child)
        {
            this._text_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._textlist_ == oldChild)
        {
            setTextlist((PTextlist) newChild);
            return;
        }

        if(this._text_ == oldChild)
        {
            setText((TText) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
