/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.parser;

import srt.lexer.*;
import srt.node.*;
import srt.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PFilesub node1 = (PFilesub) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AFilesub */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AItemItemlist */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AItemlistItemlist */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce AItem */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce ATime */
            {
                ArrayList<Object> list = new4();
                push(goTo(3), list, false);
            }
            break;
            case 5: /* reduce ATextlistSubs */
            {
                ArrayList<Object> list = new5();
                push(goTo(4), list, false);
            }
            break;
            case 6: /* reduce AEffectSubs */
            {
                ArrayList<Object> list = new6();
                push(goTo(4), list, false);
            }
            break;
            case 7: /* reduce ATextTextlist */
            {
                ArrayList<Object> list = new7();
                push(goTo(5), list, false);
            }
            break;
            case 8: /* reduce ATextlistTextlist */
            {
                ArrayList<Object> list = new8();
                push(goTo(5), list, false);
            }
            break;
            case 9: /* reduce ATextEffect */
            {
                ArrayList<Object> list = new9();
                push(goTo(6), list, false);
            }
            break;
            case 10: /* reduce ASlashEffect */
            {
                ArrayList<Object> list = new10();
                push(goTo(6), list, false);
            }
            break;
            case 11: /* reduce AHours */
            {
                ArrayList<Object> list = new11();
                push(goTo(7), list, false);
            }
            break;
            case 12: /* reduce AMinutes */
            {
                ArrayList<Object> list = new12();
                push(goTo(8), list, false);
            }
            break;
            case 13: /* reduce ASeconds */
            {
                ArrayList<Object> list = new13();
                push(goTo(9), list, false);
            }
            break;
            case 14: /* reduce AMillisecons */
            {
                ArrayList<Object> list = new14();
                push(goTo(10), list, false);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AFilesub */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFilesub pfilesubNode1;
        {
            // Block
        PItemlist pitemlistNode2;
        pitemlistNode2 = (PItemlist)nodeArrayList1.get(0);

        pfilesubNode1 = new AFilesub(pitemlistNode2);
        }
	nodeList.add(pfilesubNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AItemItemlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItemlist pitemlistNode1;
        {
            // Block
        PItem pitemNode2;
        pitemNode2 = (PItem)nodeArrayList1.get(0);

        pitemlistNode1 = new AItemItemlist(pitemNode2);
        }
	nodeList.add(pitemlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AItemlistItemlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItemlist pitemlistNode1;
        {
            // Block
        PItemlist pitemlistNode2;
        PItem pitemNode3;
        pitemlistNode2 = (PItemlist)nodeArrayList1.get(0);
        pitemNode3 = (PItem)nodeArrayList2.get(0);

        pitemlistNode1 = new AItemlistItemlist(pitemlistNode2, pitemNode3);
        }
	nodeList.add(pitemlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AItem */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem pitemNode1;
        {
            // Block
        TNum tnumNode2;
        PTime ptimeNode3;
        PSubs psubsNode4;
        tnumNode2 = (TNum)nodeArrayList1.get(0);
        ptimeNode3 = (PTime)nodeArrayList2.get(0);
        psubsNode4 = (PSubs)nodeArrayList3.get(0);

        pitemNode1 = new AItem(tnumNode2, ptimeNode3, psubsNode4);
        }
	nodeList.add(pitemNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ATime */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList15 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTime ptimeNode1;
        {
            // Block
        PHours phoursNode2;
        TTwopoint ttwopointNode3;
        PMinutes pminutesNode4;
        TTwopoint ttwopointNode5;
        PSeconds psecondsNode6;
        TComma tcommaNode7;
        PMillisecons pmilliseconsNode8;
        TArrow tarrowNode9;
        PHours phoursNode10;
        TTwopoint ttwopointNode11;
        PMinutes pminutesNode12;
        TTwopoint ttwopointNode13;
        PSeconds psecondsNode14;
        TComma tcommaNode15;
        PMillisecons pmilliseconsNode16;
        phoursNode2 = (PHours)nodeArrayList1.get(0);
        ttwopointNode3 = (TTwopoint)nodeArrayList2.get(0);
        pminutesNode4 = (PMinutes)nodeArrayList3.get(0);
        ttwopointNode5 = (TTwopoint)nodeArrayList4.get(0);
        psecondsNode6 = (PSeconds)nodeArrayList5.get(0);
        tcommaNode7 = (TComma)nodeArrayList6.get(0);
        pmilliseconsNode8 = (PMillisecons)nodeArrayList7.get(0);
        tarrowNode9 = (TArrow)nodeArrayList8.get(0);
        phoursNode10 = (PHours)nodeArrayList9.get(0);
        ttwopointNode11 = (TTwopoint)nodeArrayList10.get(0);
        pminutesNode12 = (PMinutes)nodeArrayList11.get(0);
        ttwopointNode13 = (TTwopoint)nodeArrayList12.get(0);
        psecondsNode14 = (PSeconds)nodeArrayList13.get(0);
        tcommaNode15 = (TComma)nodeArrayList14.get(0);
        pmilliseconsNode16 = (PMillisecons)nodeArrayList15.get(0);

        ptimeNode1 = new ATime(phoursNode2, ttwopointNode3, pminutesNode4, ttwopointNode5, psecondsNode6, tcommaNode7, pmilliseconsNode8, tarrowNode9, phoursNode10, ttwopointNode11, pminutesNode12, ttwopointNode13, psecondsNode14, tcommaNode15, pmilliseconsNode16);
        }
	nodeList.add(ptimeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ATextlistSubs */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSubs psubsNode1;
        {
            // Block
        PTextlist ptextlistNode2;
        ptextlistNode2 = (PTextlist)nodeArrayList1.get(0);

        psubsNode1 = new ATextlistSubs(ptextlistNode2);
        }
	nodeList.add(psubsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AEffectSubs */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSubs psubsNode1;
        {
            // Block
        PEffect peffectNode2;
        PTextlist ptextlistNode3;
        PEffect peffectNode4;
        peffectNode2 = (PEffect)nodeArrayList1.get(0);
        ptextlistNode3 = (PTextlist)nodeArrayList2.get(0);
        peffectNode4 = (PEffect)nodeArrayList3.get(0);

        psubsNode1 = new AEffectSubs(peffectNode2, ptextlistNode3, peffectNode4);
        }
	nodeList.add(psubsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ATextTextlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTextlist ptextlistNode1;
        {
            // Block
        TText ttextNode2;
        ttextNode2 = (TText)nodeArrayList1.get(0);

        ptextlistNode1 = new ATextTextlist(ttextNode2);
        }
	nodeList.add(ptextlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ATextlistTextlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTextlist ptextlistNode1;
        {
            // Block
        PTextlist ptextlistNode2;
        TText ttextNode3;
        ptextlistNode2 = (PTextlist)nodeArrayList1.get(0);
        ttextNode3 = (TText)nodeArrayList2.get(0);

        ptextlistNode1 = new ATextlistTextlist(ptextlistNode2, ttextNode3);
        }
	nodeList.add(ptextlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce ATextEffect */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PEffect peffectNode1;
        {
            // Block
        TPlus tplusNode2;
        TText ttextNode3;
        TMinus tminusNode4;
        tplusNode2 = (TPlus)nodeArrayList1.get(0);
        ttextNode3 = (TText)nodeArrayList2.get(0);
        tminusNode4 = (TMinus)nodeArrayList3.get(0);

        peffectNode1 = new ATextEffect(tplusNode2, ttextNode3, tminusNode4);
        }
	nodeList.add(peffectNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ASlashEffect */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PEffect peffectNode1;
        {
            // Block
        TPlus tplusNode2;
        TSlash tslashNode3;
        TText ttextNode4;
        TMinus tminusNode5;
        tplusNode2 = (TPlus)nodeArrayList1.get(0);
        tslashNode3 = (TSlash)nodeArrayList2.get(0);
        ttextNode4 = (TText)nodeArrayList3.get(0);
        tminusNode5 = (TMinus)nodeArrayList4.get(0);

        peffectNode1 = new ASlashEffect(tplusNode2, tslashNode3, ttextNode4, tminusNode5);
        }
	nodeList.add(peffectNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AHours */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PHours phoursNode1;
        {
            // Block
        TDigit tdigitNode2;
        TDigit tdigitNode3;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);
        tdigitNode3 = (TDigit)nodeArrayList2.get(0);

        phoursNode1 = new AHours(tdigitNode2, tdigitNode3);
        }
	nodeList.add(phoursNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AMinutes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMinutes pminutesNode1;
        {
            // Block
        TDigit tdigitNode2;
        TDigit tdigitNode3;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);
        tdigitNode3 = (TDigit)nodeArrayList2.get(0);

        pminutesNode1 = new AMinutes(tdigitNode2, tdigitNode3);
        }
	nodeList.add(pminutesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ASeconds */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSeconds psecondsNode1;
        {
            // Block
        TDigit tdigitNode2;
        TDigit tdigitNode3;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);
        tdigitNode3 = (TDigit)nodeArrayList2.get(0);

        psecondsNode1 = new ASeconds(tdigitNode2, tdigitNode3);
        }
	nodeList.add(psecondsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AMillisecons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMillisecons pmilliseconsNode1;
        {
            // Block
        TDigit tdigitNode2;
        TDigit tdigitNode3;
        tdigitNode2 = (TDigit)nodeArrayList1.get(0);
        tdigitNode3 = (TDigit)nodeArrayList2.get(0);

        pmilliseconsNode1 = new AMillisecons(tdigitNode2, tdigitNode3);
        }
	nodeList.add(pmilliseconsNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {4, SHIFT, 5}, },
			{{-1, ERROR, 2}, {9, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 5}, {4, SHIFT, 9}, },
			{{-1, ERROR, 6}, {5, SHIFT, 10}, {6, SHIFT, 11}, },
			{{-1, ERROR, 7}, {3, SHIFT, 15}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 11}, {5, SHIFT, 16}, {7, SHIFT, 17}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 5}, {5, SHIFT, 18}, },
			{{-1, ERROR, 14}, {5, SHIFT, 10}, },
			{{-1, ERROR, 15}, {4, SHIFT, 20}, },
			{{-1, ERROR, 16}, {8, SHIFT, 22}, },
			{{-1, ERROR, 17}, {5, SHIFT, 23}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 19}, {5, SHIFT, 18}, {6, SHIFT, 11}, },
			{{-1, ERROR, 20}, {4, SHIFT, 25}, },
			{{-1, ERROR, 21}, {3, SHIFT, 26}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 23}, {8, SHIFT, 27}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 26}, {4, SHIFT, 28}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 28}, {4, SHIFT, 30}, },
			{{-1, ERROR, 29}, {2, SHIFT, 31}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 31}, {4, SHIFT, 32}, },
			{{-1, ERROR, 32}, {4, SHIFT, 34}, },
			{{-1, ERROR, 33}, {1, SHIFT, 35}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 35}, {4, SHIFT, 5}, },
			{{-1, ERROR, 36}, {3, SHIFT, 37}, },
			{{-1, ERROR, 37}, {4, SHIFT, 20}, },
			{{-1, ERROR, 38}, {3, SHIFT, 39}, },
			{{-1, ERROR, 39}, {4, SHIFT, 28}, },
			{{-1, ERROR, 40}, {2, SHIFT, 41}, },
			{{-1, ERROR, 41}, {4, SHIFT, 32}, },
			{{-1, REDUCE, 4}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 4}, {3, 8}, },
			{{-1, 6}, },
			{{-1, 12}, },
			{{-1, 13}, {14, 19}, },
			{{-1, 14}, {19, 24}, },
			{{-1, 7}, {35, 36}, },
			{{-1, 21}, {37, 38}, },
			{{-1, 29}, {39, 40}, },
			{{-1, 33}, {41, 42}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: num",
			"expecting: digit",
			"expecting: EOF",
			"expecting: num, EOF",
			"expecting: text, '<'",
			"expecting: ':'",
			"expecting: num, text, '<', EOF",
			"expecting: text, '/'",
			"expecting: num, text, EOF",
			"expecting: text",
			"expecting: '>'",
			"expecting: ','",
			"expecting: arrow",
			"expecting: arrow, text, '<'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 1, 4, 5, 3, 5, 6, 7, 3, 8, 9, 1, 10, 9, 6, 4, 1, 5, 8, 10, 3, 5, 1, 8, 1, 11, 11, 1, 1, 12, 13, 1, 5, 1, 5, 1, 11, 1, 4, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
