/* This file was generated by SableCC (http://www.sablecc.org/). */

package subtitulo.node;

import subtitulo.analysis.*;

@SuppressWarnings("nls")
public final class AItemlistItemlist extends PItemlist
{
    private PItemlist _itemlist_;
    private PItem _item_;

    public AItemlistItemlist()
    {
        // Constructor
    }

    public AItemlistItemlist(
        @SuppressWarnings("hiding") PItemlist _itemlist_,
        @SuppressWarnings("hiding") PItem _item_)
    {
        // Constructor
        setItemlist(_itemlist_);

        setItem(_item_);

    }

    @Override
    public Object clone()
    {
        return new AItemlistItemlist(
            cloneNode(this._itemlist_),
            cloneNode(this._item_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAItemlistItemlist(this);
    }

    public PItemlist getItemlist()
    {
        return this._itemlist_;
    }

    public void setItemlist(PItemlist node)
    {
        if(this._itemlist_ != null)
        {
            this._itemlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._itemlist_ = node;
    }

    public PItem getItem()
    {
        return this._item_;
    }

    public void setItem(PItem node)
    {
        if(this._item_ != null)
        {
            this._item_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._itemlist_)
            + toString(this._item_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._itemlist_ == child)
        {
            this._itemlist_ = null;
            return;
        }

        if(this._item_ == child)
        {
            this._item_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._itemlist_ == oldChild)
        {
            setItemlist((PItemlist) newChild);
            return;
        }

        if(this._item_ == oldChild)
        {
            setItem((PItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
