/* This file was generated by SableCC (http://www.sablecc.org/). */

package subtitulo.node;

import subtitulo.analysis.*;

@SuppressWarnings("nls")
public final class AItem extends PItem
{
    private TDigit _digit_;
    private PTime _time_;
    private PSubs _subs_;

    public AItem()
    {
        // Constructor
    }

    public AItem(
        @SuppressWarnings("hiding") TDigit _digit_,
        @SuppressWarnings("hiding") PTime _time_,
        @SuppressWarnings("hiding") PSubs _subs_)
    {
        // Constructor
        setDigit(_digit_);

        setTime(_time_);

        setSubs(_subs_);

    }

    @Override
    public Object clone()
    {
        return new AItem(
            cloneNode(this._digit_),
            cloneNode(this._time_),
            cloneNode(this._subs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAItem(this);
    }

    public TDigit getDigit()
    {
        return this._digit_;
    }

    public void setDigit(TDigit node)
    {
        if(this._digit_ != null)
        {
            this._digit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._digit_ = node;
    }

    public PTime getTime()
    {
        return this._time_;
    }

    public void setTime(PTime node)
    {
        if(this._time_ != null)
        {
            this._time_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._time_ = node;
    }

    public PSubs getSubs()
    {
        return this._subs_;
    }

    public void setSubs(PSubs node)
    {
        if(this._subs_ != null)
        {
            this._subs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._digit_)
            + toString(this._time_)
            + toString(this._subs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._digit_ == child)
        {
            this._digit_ = null;
            return;
        }

        if(this._time_ == child)
        {
            this._time_ = null;
            return;
        }

        if(this._subs_ == child)
        {
            this._subs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._digit_ == oldChild)
        {
            setDigit((TDigit) newChild);
            return;
        }

        if(this._time_ == oldChild)
        {
            setTime((PTime) newChild);
            return;
        }

        if(this._subs_ == oldChild)
        {
            setSubs((PSubs) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
