/* This file was generated by SableCC (http://www.sablecc.org/). */

package subtitulo.node;

import subtitulo.analysis.*;

@SuppressWarnings("nls")
public final class ATextSubs extends PSubs
{
    private PWriting _writing_;

    public ATextSubs()
    {
        // Constructor
    }

    public ATextSubs(
        @SuppressWarnings("hiding") PWriting _writing_)
    {
        // Constructor
        setWriting(_writing_);

    }

    @Override
    public Object clone()
    {
        return new ATextSubs(
            cloneNode(this._writing_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextSubs(this);
    }

    public PWriting getWriting()
    {
        return this._writing_;
    }

    public void setWriting(PWriting node)
    {
        if(this._writing_ != null)
        {
            this._writing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._writing_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._writing_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._writing_ == child)
        {
            this._writing_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._writing_ == oldChild)
        {
            setWriting((PWriting) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
