/* This file was generated by SableCC (http://www.sablecc.org/). */

package subtitulo.node;

import subtitulo.analysis.*;

@SuppressWarnings("nls")
public final class TClose extends Token
{
    public TClose()
    {
        super.setText("</font>");
    }

    public TClose(int line, int pos)
    {
        super.setText("</font>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TClose(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClose(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TClose text.");
    }
}
